### ISSUE TITLE
nginx配置解析中Configuration能否提供将*parser.Config导出方法

### ISSUE THREAD

**Issue by liulanghai** [ClessLi/bifrost#5]
当前Configuration指提供Json等方法输出序列化的nginx配置，能否提供将 type configuration struct {
	config        *parser.Config
	rwLocker      *sync.RWMutex
	loopPreventer loop_preventer.LoopPreventer
	utils.ConfigFingerprinter
}中的config导出的接口

**Comment by ClessLi** [comment]
是需要parser.Config.Dump(dumper dumper.Dumper) error 这个方法还是仅需要导出各个配置文件，如果是后者，configuration.Configuration.Dump() map[string][]byte 方法提供了key为配置文件路径，value为配置文件内容bytes切片。

**Comment by liulanghai** [comment]
都不是，是直接导出 *parse.Config. 我这边需求是想获取这个之后做一些其他事情，比如配置检查，不同ngixn配置对比差异

**Comment by ClessLi** [comment]
> 都不是，是直接导出 *parse.Config. 我这边需求是想获取这个之后做一些其他事情，比如配置检查，不同ngixn配置对比差异

哦，也是可以的，Configuration接口类继承了Querier类，可以使用Querier.Self()方法得到parser.Parser类：

**Comment by ClessLi** [comment]
> 都不是，是直接导出 *parse.Config. 我这边需求是想获取这个之后做一些其他事情，比如配置检查，不同ngixn配置对比差异

看是否解决了该需求，OK的话就先关闭该issue了
